# Generated by Django 5.1.1 on 2024-10-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('time_range_start', models.DateTimeField()),
                ('time_range_end', models.DateTimeField()),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
